version: '3.8'

services:
  master-order:
    build: .
    container_name: master-order
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      # Persistent data storage - Updated paths for Unraid
      - /mnt/user/appdata/master-order/data:/app/data
      - /mnt/user/appdata/master-order/artwork-cache:/app/server/artwork-cache
      - /mnt/user/appdata/master-order/logs:/app/logs
      # Optional: Mount Plex media paths if running on same server
      # - /mnt/user/Media:/media:ro
    environment:
      - NODE_ENV=production
      # Connect to PostgreSQL using Unraid IP address
      - "DATABASE_URL=postgresql://master_order_user:secure_password_change_me@192.168.1.113:5432/master_order"
      - "POSTGRES_PASSWORD=secure_password_change_me"
      - PORT=3001
      # Temporarily skip PostgreSQL readiness check for debugging
      - SKIP_PG_CHECK=true
      # Add your API keys and settings here or use a .env file
      # - PLEX_URL=http://your-plex-server:32400
      # - PLEX_TOKEN=your-plex-token
      # - TVDB_API_KEY=your-tvdb-api-key
      # - COMICVINE_API_KEY=your-comicvine-api-key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  master-order-data:
  master-order-artwork:
  master-order-logs:
