-- AlterTable
ALTER TABLE "Settings" ADD COLUMN "timezone" TEXT DEFAULT 'UTC';

-- CreateTable
CREATE TABLE "PlexArtist" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "ratingKey" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "guid" TEXT,
    "type" TEXT NOT NULL DEFAULT 'artist',
    "title" TEXT NOT NULL,
    "titleSort" TEXT,
    "summary" TEXT,
    "index" INTEGER,
    "rating" REAL,
    "audienceRating" REAL,
    "userRating" REAL,
    "viewCount" INTEGER,
    "lastViewedAt" INTEGER,
    "addedAt" INTEGER,
    "updatedAt_plex" INTEGER,
    "thumb" TEXT,
    "art" TEXT,
    "theme" TEXT,
    "musicAnalysisVersion" INTEGER,
    "albumSort" INTEGER,
    "locations" TEXT,
    "genres" TEXT,
    "styles" TEXT,
    "moods" TEXT,
    "collections" TEXT,
    "countries" TEXT,
    "similar" TEXT,
    "sectionKey" TEXT NOT NULL,
    "librarySectionID" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "PlexArtist_sectionKey_fkey" FOREIGN KEY ("sectionKey") REFERENCES "PlexLibrarySection" ("sectionKey") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PlexAlbum" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "ratingKey" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "parentRatingKey" TEXT NOT NULL,
    "guid" TEXT,
    "parentGuid" TEXT,
    "type" TEXT NOT NULL DEFAULT 'album',
    "title" TEXT NOT NULL,
    "titleSort" TEXT,
    "parentTitle" TEXT,
    "summary" TEXT,
    "index" INTEGER,
    "rating" REAL,
    "audienceRating" REAL,
    "userRating" REAL,
    "viewCount" INTEGER,
    "viewedLeafCount" INTEGER,
    "leafCount" INTEGER,
    "lastViewedAt" INTEGER,
    "addedAt" INTEGER,
    "updatedAt_plex" INTEGER,
    "originallyAvailableAt" TEXT,
    "year" INTEGER,
    "thumb" TEXT,
    "art" TEXT,
    "parentThumb" TEXT,
    "parentArt" TEXT,
    "parentTheme" TEXT,
    "musicAnalysisVersion" INTEGER,
    "loudnessAnalysisVersion" INTEGER,
    "studio" TEXT,
    "genres" TEXT,
    "styles" TEXT,
    "moods" TEXT,
    "collections" TEXT,
    "formats" TEXT,
    "subformats" TEXT,
    "sectionKey" TEXT NOT NULL,
    "librarySectionID" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "PlexAlbum_sectionKey_fkey" FOREIGN KEY ("sectionKey") REFERENCES "PlexLibrarySection" ("sectionKey") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PlexAlbum_parentRatingKey_fkey" FOREIGN KEY ("parentRatingKey") REFERENCES "PlexArtist" ("ratingKey") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PlexTrack" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "ratingKey" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "parentRatingKey" TEXT NOT NULL,
    "grandparentRatingKey" TEXT NOT NULL,
    "guid" TEXT,
    "parentGuid" TEXT,
    "grandparentGuid" TEXT,
    "type" TEXT NOT NULL DEFAULT 'track',
    "title" TEXT NOT NULL,
    "titleSort" TEXT,
    "originalTitle" TEXT,
    "parentTitle" TEXT,
    "grandparentTitle" TEXT,
    "summary" TEXT,
    "index" INTEGER,
    "parentIndex" INTEGER,
    "rating" REAL,
    "audienceRating" REAL,
    "userRating" REAL,
    "ratingCount" INTEGER,
    "viewCount" INTEGER,
    "skipCount" INTEGER,
    "lastViewedAt" INTEGER,
    "addedAt" INTEGER,
    "updatedAt_plex" INTEGER,
    "year" INTEGER,
    "duration" INTEGER,
    "viewOffset" INTEGER,
    "thumb" TEXT,
    "art" TEXT,
    "parentThumb" TEXT,
    "parentArt" TEXT,
    "grandparentThumb" TEXT,
    "grandparentArt" TEXT,
    "grandparentTheme" TEXT,
    "musicAnalysisVersion" INTEGER,
    "chapterSource" TEXT,
    "primaryExtraKey" TEXT,
    "sourceURI" TEXT,
    "genres" TEXT,
    "collections" TEXT,
    "media" TEXT,
    "chapters" TEXT,
    "sectionKey" TEXT NOT NULL,
    "librarySectionID" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "PlexTrack_sectionKey_fkey" FOREIGN KEY ("sectionKey") REFERENCES "PlexLibrarySection" ("sectionKey") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PlexTrack_parentRatingKey_fkey" FOREIGN KEY ("parentRatingKey") REFERENCES "PlexAlbum" ("ratingKey") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PlexTrack_grandparentRatingKey_fkey" FOREIGN KEY ("grandparentRatingKey") REFERENCES "PlexArtist" ("ratingKey") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "PlexArtist_ratingKey_key" ON "PlexArtist"("ratingKey");

-- CreateIndex
CREATE UNIQUE INDEX "PlexAlbum_ratingKey_key" ON "PlexAlbum"("ratingKey");

-- CreateIndex
CREATE UNIQUE INDEX "PlexTrack_ratingKey_key" ON "PlexTrack"("ratingKey");
