-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_CustomOrderItem" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "customOrderId" INTEGER NOT NULL,
    "mediaType" TEXT NOT NULL,
    "plexKey" TEXT,
    "title" TEXT NOT NULL,
    "seasonNumber" INTEGER,
    "episodeNumber" INTEGER,
    "seriesTitle" TEXT,
    "comicSeries" TEXT,
    "comicYear" INTEGER,
    "comicIssue" TEXT,
    "comicVolume" TEXT,
    "comicVineId" TEXT,
    "comicVineDetailsJson" TEXT,
    "customTitle" TEXT,
    "bookTitle" TEXT,
    "bookAuthor" TEXT,
    "bookYear" INTEGER,
    "bookIsbn" TEXT,
    "bookPublisher" TEXT,
    "bookOpenLibraryId" TEXT,
    "bookCoverUrl" TEXT,
    "storyTitle" TEXT,
    "storyAuthor" TEXT,
    "storyYear" INTEGER,
    "storyUrl" TEXT,
    "storyContainedInBookId" INTEGER,
    "storyCoverUrl" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isWatched" BOOLEAN NOT NULL DEFAULT false,
    "isFromTvdbOnly" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "artworkLastCached" DATETIME,
    "artworkMimeType" TEXT,
    "localArtworkPath" TEXT,
    "originalArtworkUrl" TEXT,
    "webTitle" TEXT,
    "webUrl" TEXT,
    "webDescription" TEXT,
    "tvdbId" TEXT,
    "tvdbYear" INTEGER,
    "tvdbOverview" TEXT,
    "tvdbGenres" TEXT,
    "tvdbDirector" TEXT,
    "tvdbStudio" TEXT,
    "tvdbArtworkUrl" TEXT,
    "referencedCustomOrderId" INTEGER,
    CONSTRAINT "CustomOrderItem_storyContainedInBookId_fkey" FOREIGN KEY ("storyContainedInBookId") REFERENCES "CustomOrderItem" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "CustomOrderItem_referencedCustomOrderId_fkey" FOREIGN KEY ("referencedCustomOrderId") REFERENCES "CustomOrder" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "CustomOrderItem_customOrderId_fkey" FOREIGN KEY ("customOrderId") REFERENCES "CustomOrder" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_CustomOrderItem" ("artworkLastCached", "artworkMimeType", "bookAuthor", "bookCoverUrl", "bookIsbn", "bookOpenLibraryId", "bookPublisher", "bookTitle", "bookYear", "comicIssue", "comicSeries", "comicVineDetailsJson", "comicVineId", "comicVolume", "comicYear", "createdAt", "customOrderId", "customTitle", "episodeNumber", "id", "isFromTvdbOnly", "isWatched", "localArtworkPath", "mediaType", "originalArtworkUrl", "plexKey", "seasonNumber", "seriesTitle", "sortOrder", "storyAuthor", "storyContainedInBookId", "storyCoverUrl", "storyTitle", "storyUrl", "storyYear", "title", "tvdbArtworkUrl", "tvdbDirector", "tvdbGenres", "tvdbId", "tvdbOverview", "tvdbStudio", "tvdbYear", "updatedAt", "webDescription", "webTitle", "webUrl") SELECT "artworkLastCached", "artworkMimeType", "bookAuthor", "bookCoverUrl", "bookIsbn", "bookOpenLibraryId", "bookPublisher", "bookTitle", "bookYear", "comicIssue", "comicSeries", "comicVineDetailsJson", "comicVineId", "comicVolume", "comicYear", "createdAt", "customOrderId", "customTitle", "episodeNumber", "id", "isFromTvdbOnly", "isWatched", "localArtworkPath", "mediaType", "originalArtworkUrl", "plexKey", "seasonNumber", "seriesTitle", "sortOrder", "storyAuthor", "storyContainedInBookId", "storyCoverUrl", "storyTitle", "storyUrl", "storyYear", "title", "tvdbArtworkUrl", "tvdbDirector", "tvdbGenres", "tvdbId", "tvdbOverview", "tvdbStudio", "tvdbYear", "updatedAt", "webDescription", "webTitle", "webUrl" FROM "CustomOrderItem";
DROP TABLE "CustomOrderItem";
ALTER TABLE "new_CustomOrderItem" RENAME TO "CustomOrderItem";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
